# browsers.sh -- all four of them, not just the one that was interesting.
#
# The complaint this is built around: "all browsers have some level of
# transparency which is ok, but not always pretty."
#
# That is two separate statements and they need two separate assertions.
#
#   Every browser IS translucent, because bin/noct-glass fades every window
#   through the compositor and a browser is a window. Nothing in a browser has
#   to agree to that and nothing can opt out of it.
#
#   Only Zen is translucent BY ITSELF. Its page area is transparent -- that is
#   the "transparent zen" mod plus zen.widget.linux.transparency -- so whatever
#   the compositor does to the window, the page has its own alpha on top of it.
#   The other three paint an opaque page background and always will.
#
# So Zen sits at `browser` x `window` and the rest sit at `window`, and with
# the levels as they are that is not a small difference: it is the difference
# between two windows that read as the same material and two that do not. That
# is what "not always pretty" is, and it is the parity assertion below.
#
# Every measurement here is taken on a browser this suite started itself,
# against a throwaway profile. See tests/lib/probe.sh for why -- the short
# version is that a Firefox-family browser reads its configuration exactly once,
# at startup, so a running one is evidence about the past.

noct_register zen-sheet      pure check_zen_sheet \
    "the generated Zen stylesheet is at the right alpha and out-specifies the mod"
noct_register browser-glass  live check_browser_glass \
    "every installed browser is translucent to the degree the config intends"

# Two surfaces further apart than this read as two materials rather than one.
#
# The number is not taste. The compositor dims an UNFOCUSED window by 0.06
# (write_hypr in bin/noct-glass), so any two windows more than 0.06 apart look
# exactly like the same window in two different focus states -- which is
# precisely the "zen when active looks like kitty when inactive" report that
# the browser level was introduced to fix.
BROWSER_SPREAD_MAX=${BROWSER_SPREAD_MAX:-0.06}

# ---------------------------------------------------------------------------
# zen-sheet -- static, and the half of the Zen story a measurement cannot see.
#
# The generated stylesheet has to beat a rule that belongs to somebody else's
# extension. The mod paints the same element !important from a 0-3-1 selector,
# so a plain `:root .browserStack > browser` at 0-2-1 loses silently and the
# page keeps the mod's wash. Nothing reports it; the page simply looks wrong.
#
# This is checked by comparing the selectors rather than by measuring, because
# a throwaway profile does not carry the mod -- so the live check cannot see
# this conflict at all. The two checks together cover what neither does alone.
# ---------------------------------------------------------------------------

check_zen_sheet() {
    local profiles
    profiles=$(noct_managed_profiles zen)
    [[ -n $profiles ]] || { skip zen-sheet "no Zen profile carries this repo's user.js"; return; }

    local win browser want
    read -r win _ browser <<<"$(noct_glass_levels)"
    want=$(awk -v b="$browser" -v w="$win" 'BEGIN { f = b / w; if (f > 1) f = 1; printf "%.2f", f }')

    local prof sheet alpha problems=()
    while IFS= read -r prof; do
        [[ -n $prof ]] || continue
        sheet=$prof/chrome/userChrome.css

        if [[ ! -f $sheet ]]; then
            problems+=("${prof##*/}: no chrome/userChrome.css -- run 'noct-glass apply'")
            continue
        fi
        if ! grep -q "Generated by noct-glass" "$sheet"; then
            problems+=("${prof##*/}: userChrome.css is not ours and was left alone")
            continue
        fi
        if ! grep -q 'toolkit.legacyUserProfileCustomizations.stylesheets", *true' "$prof/user.js"; then
            problems+=("${prof##*/}: user.js does not enable legacy stylesheets, so the sheet is never read")
        fi

        alpha=$(sed -n 's/.*rgba([0-9]*, *[0-9]*, *[0-9]*, *\([0-9.]*\)).*/\1/p' "$sheet" | head -1)
        if ! num_eq "${alpha:-0}" "$want"; then
            problems+=("${prof##*/}: sheet is at alpha ${alpha:-none}, should be $want for browser $browser / window $win")
        fi

        # Specificity, for every rule that paints the page area. The mod's is
        # 0-3-1; a tie goes to whoever is later in the cascade, which is not
        # something we control, so this wants a strict win.
        local weak
        weak=$(awk '
            # Selector lines only. The file explains the specificity problem in
            # its own header, so a naive grep for the selector finds the prose
            # describing the bug and reports it as the bug.
            /^[[:space:]]*[^*\/[:space:]]/ && /\.browserStack *> *browser/ && /\{[[:space:]]*$/ {
                sel = $0
                sub(/\{.*/, "", sel)
                ids = gsub(/#/, "#", sel)
                cls = gsub(/\./, ".", sel) + gsub(/\[/, "[", sel) + gsub(/:/, ":", sel)
                if (ids == 0 && cls <= 3) print "  " sel
            }' "$sheet")
        [[ -n $weak ]] && problems+=("${prof##*/}: a page-area selector does not beat the transparency mod's 0-3-1:$weak")
    done <<<"$profiles"

    metric browser.sheet_alpha "$want" 0.01

    if (( ${#problems[@]} == 0 )); then
        pass zen-sheet "every managed profile has our sheet at alpha $want, out-specifying the mod"
    else
        fail zen-sheet "${#problems[@]} problem(s) with the generated Zen stylesheet"
        local pr; for pr in "${problems[@]}"; do info "$pr"; done
    fi
}

# ---------------------------------------------------------------------------
# browser-glass
#
# One number per browser: how much of the wallpaper reaches your eye through an
# ordinary web page. Measured, not derived, on a browser this suite started
# itself, showing a page that paints an opaque white background -- because that
# is what every page you look at does.
#
# Three captures, at the configured window level and at the two calibration
# levels, and noct_solve turns them into the position of the configured one on
# the line between the other two. For a page that paints its own background
# that position IS the effective opacity of the window.
#
# Then a readability number, computed the same way glass-legible computes it
# for a terminal: a light page and its dark text both fade towards the same
# backdrop, so the contrast between them is the page's own contrast scaled by
# the opacity. This is what "not always pretty" is, put on a scale.
#
# And then the assertion that matters: do they all read as the same material?
# ---------------------------------------------------------------------------

check_browser_glass() {
    require_cmd browser-glass grim magick jq hyprctl || return

    local -a browsers=()
    mapfile -t browsers < <(noct_browsers_present)
    (( ${#browsers[@]} )) || { skip browser-glass "none of the four browsers is installed"; return; }

    local win term browser_level
    read -r win term browser_level <<<"$(noct_glass_levels)"

    # Borrowed once, for all of them. Every set of the level costs a config
    # write, a compositor reload and a settle, so doing it per browser would
    # triple the slowest check in the suite.
    noct_glass_borrow
    local outer; outer=$(noct_defer_mark)

    local -a measured=() problems=()
    local b addr three seen own back back_sd solved ratio backdrop backdrop_sd
    local page_bg page_text contrast

    for b in "${browsers[@]}"; do
        # Back to the configured level before each one: the first capture of a
        # measurement is the one that answers the question.
        noct_glass_reset

        # Nothing that a title match could mistake for this browser's probe.
        # See noct_close_browser: the previous browser's window outliving the
        # pid that started it is how firefox once measured 0.00.
        noct_no_probe_windows || {
            info "$b: a previous probe window is still on screen -- skipped"
            continue
        }

        local mark; mark=$(noct_defer_mark)
        noct_probe_browser "$b"
        case $? in
            0) ;;
            2) info "$b: the probe window never came to rest anywhere measurable -- skipped"
               noct_unwind_to "$mark"; continue ;;
            *) info "$b: no probe window came up within 30s -- skipped"
               noct_unwind_to "$mark"; continue ;;
        esac
        addr=$NOCT_PROBE_ADDR

        three=$(noct_measure_surface "$addr" page)
        local rc=$?
        if (( rc != 0 )); then
            case $rc in
                2) info "$b: the probe page would not hold still -- skipped" ;;
                3) info "$b: the probe window would not stay put between captures -- skipped" ;;
                *) info "$b: a capture failed -- skipped" ;;
            esac
            noct_unwind_to "$mark"
            continue
        fi
        read -r seen _ own back back_sd <<<"$three"

        solved=$(noct_solve "$seen" "$own" "$back" "$back_sd")
        read -r ratio backdrop backdrop_sd <<<"$solved"

        # A page area the same brightness as the wallpaper behind it leaves
        # nothing to divide by, and any opacity computed from it is noise. It
        # should not happen with a white page over this desktop, but it is the
        # difference between a skip and a confident wrong answer.
        if awk -v o="$own" -v bd="$backdrop" 'BEGIN { d = o - bd; if (d < 0) d = -d; exit !(d < 6) }'; then
            info "$b: the page and the backdrop are the same brightness -- nothing to measure"
            noct_unwind_to "$mark"
            continue
        fi

        # What the page and its text actually land at, and the contrast between
        # them. Both fade towards the same backdrop, so this is the page's own
        # contrast scaled by the opacity -- the wallpaper cancels out of the
        # ratio, exactly as it does for a terminal.
        read -r page_bg page_text <<<"$(awk -v a="$ratio" -v b="$backdrop" -v t="$NOCT_PAGE_TEXT_GREY" 'BEGIN {
            printf "%.0f %.0f", 255 * a + b * (1 - a), t * a + b * (1 - a)
        }')"
        contrast=$(contrast_ratio "$page_text" "$page_bg")

        metric "browser.$b.effective_opacity" "$ratio"    0.04
        metric "browser.$b.page_contrast"     "$contrast" 1.5
        measured+=("$b $ratio")

        info "$(printf '%-9s effective opacity %s over a backdrop of %s: white lands at %s, #222 text at %s, %s:1' \
                       "$b" "$ratio" "$backdrop" "$page_bg" "$page_text" "$contrast")"

        # Nothing can be MORE opaque than the compositor makes it, so anything
        # above the window level is a measurement fault rather than a finding.
        if awk -v r="$ratio" -v w="$win" 'BEGIN { exit !(r > w + 0.08) }'; then
            problems+=("$b measured $ratio, above the compositor's own $win -- that is not possible, so the measurement is wrong")
        elif awk -v r="$ratio" -v w="$win" 'BEGIN { exit !(r < w - 0.08) }'; then
            # Below the window level means something INSIDE the browser is
            # making pages translucent as well. That is a real thing -- it is
            # what the transparency mod does to Zen -- and it is worth naming,
            # because it is the whole reason one browser can look unlike the
            # rest.
            problems+=("$b composites at $ratio, well under the compositor's $win -- something in the browser is making pages translucent too")
            [[ $b == zen ]] && problems+=("  for Zen that is the transparency mod, and its level is 'browser' in glass.conf (currently $browser_level)")
        fi

        awk -v c="$contrast" 'BEGIN { exit !(c < 4.5) }' \
            && problems+=("$b puts ordinary page text at ${contrast}:1, under the 4.5:1 readability floor")

        noct_unwind_to "$mark"
    done

    noct_unwind_to "$outer"

    if (( ${#measured[@]} == 0 )); then
        skip browser-glass "no browser could be measured"
        return
    fi

    # Parity. This is the assertion the complaint is actually about.
    local lo hi spread
    read -r lo hi <<<"$(printf '%s\n' "${measured[@]}" | awk '{ v = $2
        if (NR == 1 || v < min) min = v
        if (NR == 1 || v > max) max = v } END { printf "%.2f %.2f", min, max }')"
    spread=$(awk -v a="$lo" -v b="$hi" 'BEGIN { printf "%.2f", b - a }')
    metric browser.spread "$spread" 0.03

    info "$(printf 'spread across %d measured browser(s): %s to %s = %s (want <= %s)' \
                   "${#measured[@]}" "$lo" "$hi" "$spread" "$BROWSER_SPREAD_MAX")"

    local wide=0
    awk -v s="$spread" -v m="$BROWSER_SPREAD_MAX" 'BEGIN { exit !(s > m) }' && wide=1

    if (( ${#problems[@]} == 0 && ! wide )); then
        pass browser-glass "${#measured[@]} browser(s) composite within $BROWSER_SPREAD_MAX of each other, at ${lo}-${hi}"
        return
    fi

    if (( wide )); then
        fail browser-glass "the browsers are $spread apart -- more than the $BROWSER_SPREAD_MAX that reads as one material"
    else
        fail browser-glass "${#problems[@]} finding(s) about how the browsers composite"
    fi
    local p; for p in "${problems[@]}"; do info "$p"; done

    (( wide )) || return
    info ""
    info "A browser that paints an opaque page can only be as translucent as the"
    info "compositor makes it, and the compositor has one level for every window. So a"
    info "spread means one browser is ALSO translucent by itself -- which on this setup"
    info "means Zen and its transparency mod. Two ways to close it, both in"
    info "~/.config/noctalia/glass.conf:"
    info ""
    info "  raise 'browser' towards 'window'   every browser reads as the same material,"
    info "                                     and Zen stops being the glassy one"
    info "  lower 'window' towards 'browser'   the whole desktop gets glassier, and every"
    info "                                     GTK and Qt app pays for it in text contrast"
    info "                                     -- see glass-legible"
}
